### ISSUE TITLE
bug: unneeded reconciliations for branch protection rules

### ISSUE THREAD

**Issue by iul1an** [provider-github/provider-github#27]
### What happened?

When defining branch protection rules with push restrictions, PR bypass permissions, or PR dismissal settings, discrepancies in case sensitivity between referenced GitHub usernames and their actual handles cause the repository controller to continuously detect and attempt to reconcile differences.

### How can we reproduce it?

- Create the following repository:
```
---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Organization
metadata:
  name: foo
spec:
  deletionPolicy: "Orphan"
  providerConfigRef:
    name: default
  forProvider:
    description: foo
---
apiVersion: organizations.github.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: foo
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    private: false
    forceDelete: true
    description: "test"
    orgRef:
      name: foo
    permissions:
      users:
        - user: "someUser"
          role: "push"
    branchProtectionRules:
      - branch: "main"
        enforceAdmins: true
        requiredPullRequestReviews:
          dismissStaleReviews: true
          requireCodeOwnerReviews: true
          requireLastPushApproval: true
          requiredApprovingReviewCount: 1
          bypassPullRequestAllowances:
            users:
              - someuser # actual handle  is "someUser"
          dismissalRestrictions:
            users:
              - someuser # actual handle  is "someUser"
        branchProtectionRestrictions:
          blockCreations: true
          users:
            - someuser # actual handle  is "someUser"
        requireLinearHistory: true
        requiredConversationResolution: true
        requireSignedCommits: false
```

- Insert a print statement, 
```go
fmt.Println(cmp.Diff(ghBPRToConfig, crBPRToConfig))
```
before the return statement: https://github.com/kaessert/provider-github/blob/57bf6c1e8d5c049838c3090249c38f2f01404bca/internal/controller/repository/repository.go#L212-L214

- Check the provider logs:
```
2024-09-06T13:35:05+03:00	DEBUG	provider-github	Reconciling	{"controller": "managed/repository.organizations.github.crossplane.io", "request": {"name":"foo"}}
  map[string]v1alpha1.BranchProtectionRule{
  	"main": {
  		Branch:               "main",
  		RequiredStatusChecks: nil,
  		RequiredPullRequestReviews: &v1alpha1.RequiredPullRequestReviews{
  			... // 2 identical fields
  			RequiredApprovingReviewCount: 1,
  			RequireLastPushApproval:      &true,
  			BypassPullRequestAllowances: &v1alpha1.BypassPullRequestAllowancesRequest{
- 				Users: []string{"someUser"},
+ 				Users: []string{"someuser"},
  				Teams: nil,
  				Apps:  nil,
  			},
  			DismissalRestrictions: &v1alpha1.DismissalRestrictionsRequest{
- 				Users: &[]string{"someUser"},
+ 				Users: &[]string{"someuser"},
  				Teams: nil,
  				Apps:  nil,
  			},
  		},
  		BranchProtectionRestrictions: &v1alpha1.BranchProtectionRestrictions{
  			BlockCreations: &true,
- 			Users:          []string{"someUser"},
+ 			Users:          []string{"someuser"},
  			Teams:          nil,
  			Apps:           nil,
  		},
  		EnforceAdmins:        true,
  		RequireLinearHistory: &true,
  		... // 6 identical fields
  	},
  }

```

### What environment did it happen in?
Crossplane version: v1.15.2
Provider version: 57bf6c1e8d5c049838c3090249c38f2f01404bca
